
export enum UPDATE_FILTER_TYPE {
  SET_VALUE = 'SET_VALUE',
  SET_DISTINCT_VALUES = 'SET_DISTINCT_VALUES',
  TOGGLE_DISTINCT_VALUE = 'TOGGLE_DISTINCT_VALUE',
  SET_RANGE_VALUES = 'SET_RANGE_VALUES',
  CLEAR_VALUE = 'CLEAR_VALUE',
  SET_GEO_WITHIN_VALUE = 'SET_GEO_WITHIN_VALUE'
}

export type UpdateFilterMethod = (options: any, updateFilterType: UPDATE_FILTER_TYPE) => void;
