export enum SSH_TUNNEL_OPTION_ID {
  NO_SSH_TUNNEL_ROLE = 'NO_SSH_TUNNEL_ROLE',
  PASSWORD_SSH_TUNNEL_ROLE = 'PASSWORD_SSH_TUNNEL_ROLE',
  IDENTITY_FILE_SSH_TUNNEL_ROLE = 'IDENTITY_FILE_SSH_TUNNEL_ROLE'
}

type SSHTunnelOption = {
  id: SSH_TUNNEL_OPTION_ID;
  title: string;
};

export const SSHTunnelOptions: SSHTunnelOption[] = [{
  id: SSH_TUNNEL_OPTION_ID.NO_SSH_TUNNEL_ROLE,
  title: 'None'
}, {
  id: SSH_TUNNEL_OPTION_ID.PASSWORD_SSH_TUNNEL_ROLE,
  title: 'Use Password'
}, {
  id: SSH_TUNNEL_OPTION_ID.IDENTITY_FILE_SSH_TUNNEL_ROLE,
  title: 'Use Identity File'
}];
